## MAKING THE ML PROJECT (PREDICTION SYSTEM)

In [1]:
import pandas as pd
import numpy as np

## DATA COLLECTION FROM DATASET

In [68]:
data = pd.read_csv("/content/Mumbai1.csv")
data.head()

,Unnamed: 0,Price,Area,Location,No. of Bedrooms,New/Resale,Gymnasium,Lift Available,Car Parking,Maintenance Staff,24x7 Security,Children's Play Area,Clubhouse,Intercom,Landscaped Gardens,Indoor Games,Gas Connection,Jogging Track,Swimming Pool
0,0,4850000,720,Kharghar,1,0,0,1,1,1,1,0,0,0,0,0,0,0,0
1,1,4500000,600,Kharghar,1,0,1,1,1,1,1,0,1,0,0,0,0,1,1
2,2,6700000,650,Kharghar,1,0,1,1,1,1,1,1,1,1,0,0,0,1,1
3,3,4500000,650,Kharghar,1,0,0,1,1,1,1,0,0,1,1,0,0,0,0
4,4,5000000,665,Kharghar,1,0,0,1,1,1,1,0,0,1,1,0,0,0,0

In [69]:
data.shape

(6347, 19)

In [70]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6347 entries, 0 to 6346
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            6347 non-null   int64
 1   Price                 6347 non-null   int64
 2   Area                  6347 non-null   int64
 3   Location              6347 non-null   object
 4   No. of Bedrooms       6347 non-null   int64
 5   New/Resale            6347 non-null   int64
 6   Gymnasium             6347 non-null   int64
 7   Lift Available        6347 non-null   int64
 8   Car Parking           6347 non-null   int64
 9   Maintenance Staff     6347 non-null   int64
 10  24x7 Security         6347 non-null   int64
 11  Children's Play Area  6347 non-null   int64
 12  Clubhouse             6347 non-null   int64
 13  Intercom              6347 non-null   int64
 14  Landscaped Gardens    6347 non-null   int64
 15  Indoor Games          6347 non-null   int64
 16  Gas Connection        6347 non-null   int64
 17  Jogging Track         6347 non-null   int64
 18  Swimming Pool         6347 non-null   int64
dtypes: int64(18), object(1)
memory usage: 942.3+ KB

In [71]:
for column in data.columns:
    print(data[column].value_counts())
    print("*"*20)

0       1
4239    1
4237    1
4236    1
4235    1
       ..
2113    1
2112    1
2111    1
2110    1
6346    1
Name: Unnamed: 0, Length: 6347, dtype: int64
********************
8500000     116
9000000      93
7500000      92
4500000      88
9500000      88
           ...
52600000      1
5686000       1
7881000       1
2770000       1
2465000       1
Name: Price, Length: 979, dtype: int64
********************
650     263
1050    146
600     141
1100    138
1000     98
       ...
1487      1
1558      1
793       1
596       1
435       1
Name: Area, Length: 1140, dtype: int64
********************
Kharghar             533
Thane West           418
Mira Road East       390
Ulwe                 319
Borivali West        176
                    ...
worli sea face         1
Sea Face               1
Shiv Sagar Estate      1
Natakwala Lane         1
Padle Gaon             1
Name: Location, Length: 413, dtype: int64
********************
2    2601
1    2307
3    1201
4     190
5      39
6       7
7       2
Name: No. of Bedrooms, dtype: int64
********************
0    4178
1    2169
Name: New/Resale, dtype: int64
********************
1    3690
0    2657
Name: Gymnasium, dtype: int64
********************
1    5087
0    1260
Name: Lift Available, dtype: int64
********************
1    3573
0    2774
Name: Car Parking, dtype: int64
********************
0    4561
1    1786
Name: Maintenance Staff, dtype: int64
********************
1    3573
0    2774
Name: 24x7 Security, dtype: int64
********************
1    3550
0    2797
Name: Children's Play Area, dtype: int64
********************
0    3197
1    3150
Name: Clubhouse, dtype: int64
********************
0    3270
1    3077
Name: Intercom, dtype: int64
********************
0    4058
1    2289
Name: Landscaped Gardens, dtype: int64
********************
0    4953
1    1394
Name: Indoor Games, dtype: int64
********************
0    4804
1    1543
Name: Gas Connection, dtype: int64
********************
0    3926
1    2421
Name: Jogging Track, dtype: int64
********************
0    3438
1    2909
Name: Swimming Pool, dtype: int64
********************

In [72]:
data.isna().sum()

Unnamed: 0              0
Price                   0
Area                    0
Location                0
No. of Bedrooms         0
New/Resale              0
Gymnasium               0
Lift Available          0
Car Parking             0
Maintenance Staff       0
24x7 Security           0
Children's Play Area    0
Clubhouse               0
Intercom                0
Landscaped Gardens      0
Indoor Games            0
Gas Connection          0
Jogging Track           0
Swimming Pool           0
dtype: int64

In [73]:
data.drop(columns=['Lift Available','Car Parking','Maintenance Staff','24x7 Security','Clubhouse','Intercom','Landscaped Gardens','Jogging Track','Swimming Pool','Indoor Games','New/Resale','Gas Connection'], inplace=True)
data.head()

,Unnamed: 0,Price,Area,Location,No. of Bedrooms,Gymnasium,Children's Play Area
0,0,4850000,720,Kharghar,1,0,0
1,1,4500000,600,Kharghar,1,1,0
2,2,6700000,650,Kharghar,1,1,1
3,3,4500000,650,Kharghar,1,0,0
4,4,5000000,665,Kharghar,1,0,0

In [74]:
data.describe()

,Unnamed: 0,Price,Area,No. of Bedrooms,Gymnasium,Children's Play Area
count,6347.000000,6.347000e+03,6347.000000,6347.000000,6347.000000,6347.000000
mean,3173.000000,1.515401e+07,1004.327084,1.910036,0.581377,0.559319
std,1832.365411,2.015943e+07,556.375703,0.863304,0.493372,0.496508
min,0.000000,2.000000e+06,200.000000,1.000000,0.000000,0.000000
25%,1586.500000,5.300000e+06,650.000000,1.000000,0.000000,0.000000
50%,3173.000000,9.500000e+06,905.000000,2.000000,1.000000,1.000000
75%,4759.500000,1.750000e+07,1182.000000,2.000000,1.000000,1.000000
max,6346.000000,4.200000e+08,8511.000000,7.000000,1.000000,1.000000

In [75]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6347 entries, 0 to 6346
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            6347 non-null   int64
 1   Price                 6347 non-null   int64
 2   Area                  6347 non-null   int64
 3   Location              6347 non-null   object
 4   No. of Bedrooms       6347 non-null   int64
 5   Gymnasium             6347 non-null   int64
 6   Children's Play Area  6347 non-null   int64
dtypes: int64(6), object(1)
memory usage: 347.2+ KB

In [76]:
data.drop(columns=data.columns[0],
        axis=1,
        inplace=True)

In [77]:
data.head()

     Price  Area  Location  No. of Bedrooms  Gymnasium  Children's Play Area
0  4850000   720  Kharghar                1          0                     0
1  4500000   600  Kharghar                1          1                     0
2  6700000   650  Kharghar                1          1                     1
3  4500000   650  Kharghar                1          0                     0
4  5000000   665  Kharghar                1          0                     0

In [78]:
data['No. of Bedrooms'].unique()

array([1, 4, 3, 2, 5, 6, 7])

In [79]:
data['Area'].unique()

array([ 720,  600,  650, ...,  250, 1162,  435])

In [80]:
data['Price_per_sqft'] = data['Price']*100000/data['Area']

In [81]:
data.head()

,Price,Area,Location,No. of Bedrooms,Gymnasium,Children's Play Area,Price_per_sqft
0,4850000,720,Kharghar,1,0,0,6.736111e+08
1,4500000,600,Kharghar,1,1,0,7.500000e+08
2,6700000,650,Kharghar,1,1,1,1.030769e+09
3,4500000,650,Kharghar,1,0,0,6.923077e+08
4,5000000,665,Kharghar,1,0,0,7.518797e+08

In [82]:
data.describe()

,Price,Area,No. of Bedrooms,Gymnasium,Children's Play Area,Price_per_sqft
count,6.347000e+03,6347.000000,6347.000000,6347.000000,6347.000000,6.347000e+03
mean,1.515401e+07,1004.327084,1.910036,0.581377,0.559319,1.355547e+09
std,2.015943e+07,556.375703,0.863304,0.493372,0.496508,9.573921e+08
min,2.000000e+06,200.000000,1.000000,0.000000,0.000000,1.597444e+08
25%,5.300000e+06,650.000000,1.000000,0.000000,0.000000,7.234043e+08
50%,9.500000e+06,905.000000,2.000000,1.000000,1.000000,1.049383e+09
75%,1.750000e+07,1182.000000,2.000000,1.000000,1.000000,1.714286e+09
max,4.200000e+08,8511.000000,7.000000,1.000000,1.000000,1.099505e+10

In [83]:
data['Location'].value_counts()

Kharghar             533
Thane West           418
Mira Road East       390
Ulwe                 319
Borivali West        176
                    ...
worli sea face         1
Sea Face               1
Shiv Sagar Estate      1
Natakwala Lane         1
Padle Gaon             1
Name: Location, Length: 413, dtype: int64

In [84]:
data['Location'] = data['Location'].apply(lambda x: x.strip())
location_count = data['Location'].value_counts()
print(location_count)

Kharghar             533
Thane West           418
Mira Road East       390
Ulwe                 319
Borivali West        176
                    ...
worli sea face         1
Sea Face               1
Shiv Sagar Estate      1
Natakwala Lane         1
Padle Gaon             1
Name: Location, Length: 413, dtype: int64

In [85]:
locations_count_less_5 = location_count[location_count<=5]
locations_count_less_5

Mahalaxmi            5
Sector 5 Ulwe        5
Central Avenue       5
Majiwada thane       5
Greater Khanda       5
                    ..
worli sea face       1
Sea Face             1
Shiv Sagar Estate    1
Natakwala Lane       1
Padle Gaon           1
Name: Location, Length: 284, dtype: int64

In [86]:
data['Location'] = data['Location'].apply(lambda x:'other' if x in locations_count_less_5 else x)
data['Location'].value_counts()

Kharghar             533
other                510
Thane West           418
Mira Road East       390
Ulwe                 319
                    ...
Sector-8 Ulwe          6
Jogeshwari East        6
Mulund                 6
Sector 22 Kamothe      6
Kewale                 6
Name: Location, Length: 130, dtype: int64

In [87]:
data.rename(
    columns=({ 'No. of Bedrooms': 'bhk','Gymnasium':'GYM',"Children's Play Area":'bath','24x7 Security':'Security'}),
    inplace=True,
)
data.head()

     Price  Area  Location  bhk  GYM  bath  Price_per_sqft
0  4850000   720  Kharghar    1    0     0    6.736111e+08
1  4500000   600  Kharghar    1    1     0    7.500000e+08
2  6700000   650  Kharghar    1    1     1    1.030769e+09
3  4500000   650  Kharghar    1    0     0    6.923077e+08
4  5000000   665  Kharghar    1    0     0    7.518797e+08

Outlier Detection and removal

In [88]:
data.describe()

,Price,Area,bhk,GYM,bath,Price_per_sqft
count,6.347000e+03,6347.000000,6347.000000,6347.000000,6347.000000,6.347000e+03
mean,1.515401e+07,1004.327084,1.910036,0.581377,0.559319,1.355547e+09
std,2.015943e+07,556.375703,0.863304,0.493372,0.496508,9.573921e+08
min,2.000000e+06,200.000000,1.000000,0.000000,0.000000,1.597444e+08
25%,5.300000e+06,650.000000,1.000000,0.000000,0.000000,7.234043e+08
50%,9.500000e+06,905.000000,2.000000,1.000000,1.000000,1.049383e+09
75%,1.750000e+07,1182.000000,2.000000,1.000000,1.000000,1.714286e+09
max,4.200000e+08,8511.000000,7.000000,1.000000,1.000000,1.099505e+10

In [89]:
(data['Area']/data['bhk']).describe()

count    6347.000000
mean      537.443429
std       139.233025
min       194.333333
25%       450.000000
50%       533.333333
75%       616.833333
max      1716.666667
dtype: float64

In [90]:
data=data[((data['Area']/data['bhk']>=200))]
data.describe()

,Price,Area,bhk,GYM,bath,Price_per_sqft
count,6.345000e+03,6345.000000,6345.000000,6345.000000,6345.000000,6.345000e+03
mean,1.515582e+07,1004.459890,1.909693,0.581245,0.559180,1.355464e+09
std,2.016235e+07,556.413094,0.863223,0.493394,0.496524,9.575317e+08
min,2.000000e+06,200.000000,1.000000,0.000000,0.000000,1.597444e+08
25%,5.300000e+06,650.000000,1.000000,0.000000,0.000000,7.234043e+08
50%,9.500000e+06,905.000000,2.000000,1.000000,1.000000,1.048387e+09
75%,1.750000e+07,1182.000000,2.000000,1.000000,1.000000,1.714286e+09
max,4.200000e+08,8511.000000,7.000000,1.000000,1.000000,1.099505e+10

In [91]:
data.shape

(6345, 7)

In [92]:
data.Price_per_sqft.describe()

count    6.345000e+03
mean     1.355464e+09
std      9.575317e+08
min      1.597444e+08
25%      7.234043e+08
50%      1.048387e+09
75%      1.714286e+09
max      1.099505e+10
Name: Price_per_sqft, dtype: float64

In [93]:
def removeOutliners(df):
  df_Output = pd.DataFrame()
  for key,subdf in df.groupby('Location'):
    m = np.mean(subdf.Price_per_sqft)
    st = np.std(subdf.Price_per_sqft)
    gen_df = subdf[(subdf.Price_per_sqft>(m-st)) & (subdf.Price_per_sqft<=(m+st))]
    df_Output = pd.concat([df_Output,gen_df],ignore_index=True)
  return df_Output
data = removeOutliners(data)
data.describe()

,Price,Area,bhk,GYM,bath,Price_per_sqft
count,4.869000e+03,4869.000000,4869.000000,4869.000000,4869.000000,4.869000e+03
mean,1.332337e+07,992.750257,1.855206,0.582666,0.568495,1.236645e+09
std,1.455536e+07,516.930313,0.825950,0.493170,0.495337,7.660826e+08
min,2.000000e+06,200.000000,1.000000,0.000000,0.000000,2.222222e+08
25%,5.300000e+06,650.000000,1.000000,0.000000,0.000000,7.213115e+08
50%,9.000000e+06,910.000000,2.000000,1.000000,1.000000,9.740260e+08
75%,1.620000e+07,1160.000000,2.000000,1.000000,1.000000,1.632653e+09
max,2.300000e+08,7600.000000,7.000000,1.000000,1.000000,5.581395e+09

In [94]:
def bhk_outliners(df):
    exclude_indices=np.array([])
    for location, location_df in df.groupby('Location'):
        bhk_stats={}
        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk]={
                'mean': np.mean(bhk_df.Price_per_sqft),
                'std': np.std(bhk_df.Price_per_sqft),
                'count': bhk_df.shape[0]
            }
        for bhk,bhk_df in location_df.groupby('bhk'):
            stats=bhk_stats.get(bhk-1)
            if stats and stats['count']>5:
               exclude_indices=np.append(exclude_indices,bhk_df[bhk_df.Price_per_sqft<(stats['mean'])].index.values)
    return df.drop(exclude_indices,axis='index')

In [95]:
data=bhk_outliners(data)

In [96]:
data.shape

(3683, 7)

In [97]:
data

         Price  Area           Location  bhk  GYM  bath  Price_per_sqft
0      6200000   400             Airoli    1    0     0    1.550000e+09
2     14900000  1245             Airoli    2    0     0    1.196787e+09
3     14000000  1183             Airoli    2    1     1    1.183432e+09
4     14800000  1245             Airoli    2    0     0    1.188755e+09
5      6400000   495             Airoli    1    0     0    1.292929e+09
...        ...   ...                ...  ...  ...   ...             ...
4864   5600000  1050  taloja panchanand    2    0     0    5.333333e+08
4865  47500000  1509    vile parle west    3    0     0    3.147780e+09
4866  33500000  1073    vile parle west    2    0     0    3.122088e+09
4867  58000000  1735    vile parle west    3    0     0    3.342939e+09
4868  27500000   840    vile parle west    2    0     0    3.273810e+09

[3683 rows x 7 columns]

In [98]:
data.drop(columns=['bath','Price_per_sqft'],inplace=True)

In [99]:
data.head()

      Price  Area Location  bhk  GYM
0   6200000   400   Airoli    1    0
2  14900000  1245   Airoli    2    0
3  14000000  1183   Airoli    2    1
4  14800000  1245   Airoli    2    0
5   6400000   495   Airoli    1    0

## CLEANED DATA

In [100]:
data.to_csv("cleaned_data.csv")

In [101]:
X=data.drop(columns=['Price'])
Y=data['Price']

In [102]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [103]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [104]:
print(X_train.shape)
print(X_test.shape)

(2946, 4)
(737, 4)

## Applying Linear Regression

In [105]:
column_trans=make_column_transformer((OneHotEncoder(sparse=False),['Location']),remainder='passthrough')

In [106]:
scaler=StandardScaler()

In [107]:
lr = LinearRegression()

In [108]:
pipe= make_pipeline(column_trans,scaler,lr)

In [109]:
pipe.fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['Location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [110]:
Y_pred= pipe.predict(X_test)

In [111]:
r2_score(Y_test,Y_pred)

0.8966413165240867

## Applying Lasso

In [112]:
lasso= Lasso()

In [113]:
pipe= make_pipeline(column_trans,scaler,lr)

In [114]:
pipe.fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['Location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [115]:
Y_pred_lasso= pipe.predict(X_test)
r2_score(Y_test,Y_pred_lasso)

0.8966413165240867

## Applying Ridge

In [116]:
ridge= Ridge()

In [117]:
pipe= make_pipeline(column_trans,scaler,ridge)

In [118]:
pipe.fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['Location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [119]:
Y_pred_ridge= pipe.predict(X_test)
r2_score(Y_test,Y_pred_ridge)

0.8968390639344369

In [120]:
print("No Regularization: ",r2_score(Y_test,Y_pred))
print("Lasso: ", r2_score(Y_test,Y_pred_lasso))
print("Ridge: ", r2_score(Y_test,Y_pred_ridge))

No Regularization:  0.8966413165240867
Lasso:  0.8966413165240867
Ridge:  0.8968390639344369

In [55]:
import pickle

In [121]:
pickle.dump(pipe,open('RidgeModel.pkl','wb'))